# Generated by Django 5.2.6 on 2025-09-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emp_id", models.CharField(max_length=40)),
                ("emp_name", models.CharField(max_length=25)),
                ("emp_email", models.EmailField(max_length=254)),
                ("emp_contact", models.CharField(max_length=11)),
            ],
        ),
    ]
