# Generated by Django 5.2.6 on 2025-09-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="emp_gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                default="M",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="emp_profile",
            field=models.ImageField(blank=True, null=True, upload_to="profiles/"),
        ),
    ]
