# Generated by Django 5.2.6 on 2025-09-25 14:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0002_employee_emp_gender_employee_emp_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="emp_profile",
            field=models.ImageField(
                blank=True,
                default="profiles/default.png",
                null=True,
                upload_to="profiles/",
            ),
        ),
    ]
