# Generated by Django 5.2.6 on 2025-10-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0003_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(default="default.png", upload_to="profile_images/"),
        ),
    ]
